spring.application.name=HLuxe
server.port=8100

# DB Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/hluxe
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Default Servlet Path
server.servlet.context-path=/api/v1

# JWT
jwt.secretKey=ugwfrhbkiewbisgb3y0uefd9y32ukjbsh0uq3bkjhodhsc8ybkbouhcdkhbsdohwfekh83ibhs93bsfigh4

# Frontend
frontend.url=http://localhost:8100

#stripe
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=whsec_7a147169c969739507ab162a6320104cb8d6afdbd80ea965a862d444d0edf7b1